name: nn-env
dependencies:
  - python==3.8
  - pandas==1.2.1
  - numpy==1.19.2
  - matplotlib==3.3.4
  - Keras==2.4.3
  - opencv-python==4.5.1.48
  - seaborn==0.11.1
  - scikit-learn==0.24.1
  - mkl-service==2.3.0
  - theano==1.0.5
  - pillow==8.1.0
  - ipykernel==5.3.4
  - jupyter==1.0.0
  - jupyterlab==2.2.6
  - pip:
      - piexif==1.1.3
